# Generated by Django 4.2.5 on 2023-09-09 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0002_alter_studentfamily_emergency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfamily',
            name='emergency',
            field=models.CharField(max_length=10),
        ),
    ]
